Replace quickstart document by a link
SovereignCloudStack/cluster-stack-provider-openstack pull request #152
Opened 2024-04-17 14:26 UTC by jklippel

Currently there are two quickstart documents.
This is very confusing. There should only be
one quickstart.

This commit replaces the quickstart document in
this repository with a link to the current quickstart document in the cluster-stacks repository.

2024-05-30 08:16 UTC, michal-gubricky requested changes

2024-05-30 08:16 UTC, michal-gubricky commented on docs/quickstart.md
> +This document has moved.
```suggestion
This document has been moved.
```

2024-05-30 08:16 UTC, michal-gubricky commented on docs/quickstart.md
> +You can find the current version at <https://github.com/SovereignCloudStack/cluster-stacks/blob/main/providers/openstack/README.md>.
```suggestion
You can find the current version of the quickstart guide [here](https://github.com/SovereignCloudStack/cluster-stacks/blob/main/providers/openstack/README.md).
```

2024-05-30 15:55 UTC, jschoone commented
Hi @michal-gubricky, do you have to do anything here or is it a bug in GitHub? Because I can't see any unresolved change requests

2024-05-31 05:35 UTC, michal-gubricky commented
> Hi @michal-gubricky, do you have to do anything here or is it a bug in GitHub? Because I can't see any unresolved change requests

Everything seems to be resolved from my side now after you have applied my second suggestion as well.

2024-05-31 05:35 UTC, michal-gubricky approved these changes

2024-05-31 05:37 UTC, merged